networks:
  core:

volumes:
  pg-data:
  pgadmin-data:

services:  
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: supersecret
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - core
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    ports:
      - 9000:80
    environment:
      PGADMIN_DEFAULT_EMAIL: development@eliferpg.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - core
  jaeger:
    image: jaegertracing/opentelemetry-all-in-one
    ports:
      - 4317:4317
      - 13133:13133
      - 16686:16686
