version: '3.1'

networks:
  core:

volumes:
  pg_data:

services:
  db:
    image: docker.io/postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: supersecret
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - core
  adminer:
    image: docker.io/adminer
    ports:
      - 8080:8080
    environment:
      ADMINER_DESIGN: pepa-linha-dark
    networks:
      - core
